### ISSUE TITLE
Reflect changes in new P2Rank version in tutorials

### ISSUE THREAD

**Issue by skodapetr** [cusbg/p2rank-framework#1]
For example ```-conservation_dir``` param was replaced with ```-conservation_dirs```.
I do not have full list of changes.
We should also update the results for model.

**Comment by davidjakubec** [comment]
Hi,

I think that this Issue is part of a broader problem with the documentation/tutorials being distributed through several channels (*e.g.*, `prank -h`,  @rdk/p2rank README, this wiki) . This is related to issues https://github.com/rdk/p2rank/issues/47 and https://github.com/rdk/p2rank/issues/48 in @rdk/p2rank. As a new user, it is not clear which of the documentations is up-to-date and which should I follow. For example, should I use `-m` or `-model` and what does the option actually do in combination with `-c`? Should I specify the file extension `.groovy` when selecting a configuration? These are some of the questions I was left wondering. Though they may seem stupid or harmless, they may not be so, as **p2rank does not validate the input arguments** (https://github.com/rdk/p2rank/issues/36) -- therefore, if a user does not use the correct, up-to-date option/argument name, **no error is displayed and they won't find out unless they check the logs** (and they will then only identify the issue if they know what to look for). The `-conservation_dirs` issue described here is a specific example of this: if the old `-conservation_dir` option is used, **the specified directory is not used in any way**.

I think it would make sense to have a discussion about what each documentation channel should entail -- *e.g.*, should @rdk/p2rank be self-contained, or should it point to the wiki for turorials? Or, if there are no human resources to keep several documentations up-to-date, I think it would make sense to at least get rid of the obsolete/redundant pages.

David

**Comment by skodapetr** [comment]
We agreed that the documentation should reflect, and explicitly state, the last release.
